# RSS feeds for Retro Terminal Clock
# Lines starting with # are ignored.
# One feed block consists of name: and url: lines.

name: Herr Montag Status
url: https://status.herrmontag.de/rss/

name: pfthn.xyz
url: https://pftnhr.xyz/feed.xml